apiVersion: v1
kind: Pod
metadata:
  labels:
    run: memory-demo-2
  name: memory-demo-2
  namespace: mem-example
spec:
  containers:
  - image: polinux/stress
    name: memory-demo-2-ctr
    resources:
      requests:
        memory: "50Mi"
      limits:
        memory: "100Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
