apiVersion: v1
kind: Pod
metadata:
  labels:
    run: memory-demo-3
  name: memory-demo-3
  namespace: mem-example
spec:
  containers:
  - image: polinux/stress
    name: memory-demo-3-ctr
    resources:
      requests:
        memory: "100Gi"
      limits:
        memory: "200Gi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
