apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox-curl
  name: busybox-curl
  namespace: dev
spec:
  serviceAccount: user2
  containers:
  - command:
    - sleep
    - "3600"
    image: progrium/busybox
    name: busybox-curl
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
