apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: webapp-color
  name: webapp-color
spec:
  containers:
  - env:
    - name: APP_COLOR
      valueFrom:
        configMapKeyRef:
          key: APP_COLOR
          name: webapp-config
    image: kodekloud/webapp-color
    name: webapp-color
    ports:
    - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
