apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: echo-deploy
  name: echo-deploy
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echo-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: echo-deploy
    spec:
      containers:
      - image: k8s.gcr.io/echoserver:1.4
        name: echoserver
        resources: {}
status: {}
