apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: echo-deploy
  name: echo-deploy
  namespace: dev
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 31550
  selector:
    app: echo-deploy
  type: NodePort
status:
  loadBalancer: {}
