apiVersion: v1
kind: Pod
metadata:
  labels:
    run: default-mem-demo-3
  name: default-mem-demo-3
  namespace: default-mem-example
spec:
  containers:
  - image: nginx
    name: default-mem-demo-3-ctr
    resources:
      requests:
        memory: "128Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
