apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: default-mem-demo-2
  name: default-mem-demo-2
  namespace: default-mem-example
spec:
  containers:
  - image: nginx
    name: default-mem-demo-2
    resources:
      limits:
        memory: "1Gi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
