apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: simple-pod
  name: simple-pod
spec:
  containers:
  - command:
    - sleep
    - "5"
    image: alpine
    name: simple-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
