apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: user3-busybox
  name: user3-busybox
  namespace: dev
spec:
  serviceAccount: user3
  containers:
  - command:
    - sleep
    - "3600"
    image: progrium/busybox
    name: user3-busybox
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
